services:
  db:
    image: postgres:16
    container_name: autohub-db
    environment:
      POSTGRES_DB: autohub
      POSTGRES_USER: autohub
      POSTGRES_PASSWORD: autohub123
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
