spring:
  application:
    name: autohub-api

  datasource:
    url: ${DB_URL}
    username: autohub
    password: autohub123


  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
